- README.md
- doc.go
- examples/custom/main.go
- examples/interval-many/main.go
- examples/interval-vary/main.go
- examples/interval/main.go
- examples/memstats/main.go
- examples/rate-limit/main.go
- store/doc.go
- store/mem.go
- store/redis.go
This will be tagged as 1.0.0, the first versioned release.
> Update import directives to use gopkg.in/throttled/throttled.v1

- store/redigostore/redigostore.go
- store/storetest/storetest.go
I noticed that the current time being returned from this store looked
off, and upon [reading the docs for Redis' TIME][redis-time], it looks
like the second element in the array is actually supposed to be read as
microseconds. This patch changes the current millisecond implementation
to microseconds.
/cc @metcalf Can you sanity check this? Thanks!
[redis-time]: http://redis.io/commands/time
> Fix parsing of `TIME` in redigostore

- example_test.go
This adds a second example to the documentation which is similar to the
first, but demonstrates the granular use of the GCRARateLimiter's
RateLimit function. This should hopefully serve as a useful example for
anyone who needs access to an API that offers more fine-grain control.
> Add example demonstrating granular use of RateLimit

- example_test.go
Follows up #14. We already have an example based heavily around HTTP, so let's change the granular `GCRARateLimiter` usage example to one that isn't.
@metcalf Sorry for the extra noise here, but this follows up our discussion from earlier. The new example is still a little contrived, but it should serve to demonstrate the basics of direct usage.
> Use non-HTTP example for GCRARateLimiter

- .travis.yml
- Makefile
Although the project itself is still stable under 1.3, it appears that
one of the dependencies that we're pulling in isn't (golint [1]).
Just for convenience sake, let's solve this the easy way by just moving
the regular build to 1.7 to get us back into the green.
[1] https://travis-ci.org/throttled/throttled/jobs/140151055
> Move regular build to 1.7

- README.md
Adds a link to the throttled/gcra project, which lists various projects related
to GCRA rate limiting.
This seems like a decent compromise between supporting various other community
projects and keeping the README relatively succinct.
Thoughts @metcalf?
Fixes #24.
> Link up GCRA projects page

- store/redigostore/redigostore.go
It seems that under the current implementation we could run into a case
where the TTL is so short that we would never expire certain Redis keys
or might throw an error in the case of `SETEX`.
I think this is mostly relevant for extremely fast rates that would
replenish in less than second, so in practice probably not an issue that
most people would run into.
Here we just broaden the minimum horizon for an expiry out to one
second. Things should still work as expected because the proper TAT
value will still be in there if the key's checked after it should have
theoretically expired, and will also eventually be cleaned up by Redis.
Fixes #26.
@metcalf Can you double-check my work here?
> Never assign a Redis key's TTL to zero

- rate.go
This my humble attempt to help others avoid the same mistake I made when configuring throttled. With `MaxBurst = 0` it is best to imagine the limits as 1 per varying unit of time - instead of n per 1 second.
```
Rate{PerSec(1), 0} => 1 per second
Rate{PerSec(2), 0} => 1 per 0.5 seconds
Rate{PerSec(5), 0} => 1 per 0.2 seconds
```
So to allow 5 requests per second and to allow all of them to start at the same moment (this is the worst case) MaxBurst needs to be set to 4 to allow for 4 more requests in those first 0.2 seconds on top of the one that is allowed anyways.
> Clarify limits with MaxBurst 0

- .travis.yml
- README.md
- deprecated_test.go
- doc.go
- example_test.go
- http_test.go
- rate_test.go
- store/deprecated.go
- store/memstore/memstore.go
- store/memstore/memstore_test.go
- store/redigostore/redigostore.go
- store/redigostore/redigostore_test.go
- store/storetest/doc.go
- store/storetest/storetest.go
- varyby_test.go
We originally used `gopkg.in` for the project because V2 introduced
significant breaking changes and providing a way to easily get the V1
API would allow users to continue using that without too much additional
work.
Since then, Go's dependency management systems have advanced somewhat,
especially with the imminent introduction of the new `dep` tool which
allows dependencies to be locked to Git tags. Because `gopkg.in` does
introduce some additional complexity around building and contributing to
the project, this patch drops it in favor of using Git tags combined
with a more modern dependency management tool like `dep`. The V1 API has
also been obsolete for two years now, so it's not likely too many people
are going to need access to it anyway.
My plan here is to get this pull request …
> Stop using gopkg.in

- .travis.yml
- example_test.go
- http_test.go
- rate_test.go
As #35 was coming in, I noticed that as of Go 1.10, `go vet` complains
about the use of unkeyed fields in composite literals:
```
go vet ./...
./example_test.go:26: github.com/throttled/throttled.RateQuota composite literal uses unkeyed fields
./example_test.go:51: github.com/throttled/throttled.RateQuota composite literal uses unkeyed fields
./http_test.go:19: github.com/throttled/throttled.RateLimitResult composite literal uses unkeyed fields
./http_test.go:23: github.com/throttled/throttled.RateLimitResult composite literal uses unkeyed fields
./rate_test.go:41: github.com/throttled/throttled.RateQuota composite literal uses unkeyed fields
./rate_test.go:114: github.com/throttled/throttled.RateQuota composite literal uses unkeyed fields
```
Which is unfortunately failing the build for …
> Use named field names in composite literals

- CHANGELOG.md
- README.md
It's good hygiene to maintain a changelog so that people can figure out
what changed. This one adds a basic version with an entry for the
upcoming 2.2.0 that will include #37.
> Add `CHANGELOG.md`

- varyby.go
The HTTP server in the https://golang.org/pkg/net/http/ package sets RemoteAddr to an "IP:port" address before invoking a handler. The ":port" portion of the RemoteAddr prevents the throtteling from working as expected as soon as VaryBy{} contains "RemoteAddr: true". That's why we need to get rid of the port.
> Fixed a bug which occurrs when RemoteAddr is used

- .travis.yml
Adds 1.11 to build the matrix.
Only the last two versions of Go are technically supported according to
the official policy (so 1.11 and 1.10). We should make an effort to
support old versions for longer than that, but probably not *too* big of
an effort because upgrading Go versions tends to be quite easy.
Here we drop 1.7 and 1.8 because Golint no longer supports them and
they're failing in our build matrix. We could exempt them from Golint,
but given the above, I think it's okay to drop them in this case
instead.
> Add 1.11 to build matrix and drop 1.7 and 1.8

- varyby.go
Latest release caused a panic with the handling of `RemoteAdd`.
> Do not attempt to use or slice RemoteAddr if its empty

- varyby.go
- varyby_test.go
This isn't a documented occurrence as far as I can tell, but #51 reports
that it's possible. Either way, this is not a value that an attacker can
manipulate, so it makes to be conservative in how we handle it.
Fixes #51.
> Handle `RemoteAddr` values that don't contain a port

- .travis.yml
Adds newer versions of Go 1.12 and 1.13 to the Travis build matrix.
We also drop 1.9 and 1.10 -- unfortunately, go-redis has gone entirely
in on Go modules and doesn't work without them anymore. They were first
introduced in Go 1.11, so only our builds in 1.11+ are working.
There's probably a workaround we could use to keep the old versions
building, but it's not worth it. Throttled should still work fine on
these older versions even if they're not in the matrix, and Go users
tend to be pretty good about keeping their Go up-to-date anyway, so I
doubt we'll be affecting many people.
> Add Go 1.12, 1.13 to build matrix; drop 1.9, 1.10

- Makefile
- deprecated.go
- rate.go
- store/deprecated.go
Introduces a few changes:
* We now fail the build on lint failure with `-set_exit_status`, an
option that wasn't available when the bulk of this library was written.
* To make that possible, we fix a few minor linting problems.
* The main class of lint fix is to move over to use the recommended Go
`Deprecated: ` comment [1], which replaces our start-of-comment
deprecated comments, which allows docstrings to be in-line with Go's
conventions.
[1] https://github.com/golang/go/wiki/Deprecated
> Fail build on Lint failure + fix lint + use deprecated convention

- http_test.go
- rate_test.go
Performance is quite good.
```
$ go test -bench=.
goos: windows
goarch: amd64
pkg: github.com/throttled/throttled
BenchmarkHTTPRateLimiter-12              1841668               646 ns/op
BenchmarkRateLimit-12                    7271800               164 ns/op
PASS
ok      github.com/throttled/throttled  4.671s
```
> Add benchmark tests

- .travis.yml
- store/goredisstore/goredisstore.go
- store/goredisstore/goredisstore_test.go
The build is currently broken because goredis changed their API in a few
ways -- mostly adding context objects to all calls, but also with a few
minor type changes.
We'll want to have a better versioning strategy at some point here, but
for now, we update our goredis adapter to be compatible.
> Add context objects to goredis calls

- store/goredisstore/goredisstore.go
Hi :wave:
I think I've found a bug in the `SetIfNotExistsWithTTL` function.
A `time.Duration` represents the time as an `int64` nanosecond count ([godoc](https://pkg.go.dev/time?tab=doc#Duration)). However, we're currently creating a `time.Duration` from `ttl.Seconds`. Effectively, creating a new time.Duration 1,000,000,000 times smaller than the orginal ttl, as we're interpreting the seconds as nanoseconds.
The following playground example illustrates this: https://play.golang.org/p/8w15MOkAfC3
> Fix TTL in SetIfNotExistsWithTTL

- .github/workflows/ci.yml
- Makefile
- scripts/check_gofmt.sh
Adds a configuration file for GitHub Actions, which is largely based on
the CI runs that we're doing with Travis today.
I also modified the `Makefile` to improve it somewhat. Mainly:
* Tease apart its weirdness around grouping somewhat unrelated things
into single buckets (vet, lint, fmt all together as `lint`).
* Move a few tasks out of the `Makefile` that are unlikely to ever be
invoked by a user. These are called from GitHub Actions manually
instead.
* Add a script for invoking `gofmt` so that the build will actually fail
when there's a formatting problem.
* Add an explicit `all` target.
* Move `.PHONY` invocations to above each target.
> Add GitHub Actions and simplify the Makefile

- .github/workflows/ci.yml
Use the cache action to cache the dependencies that we pull down with
`make get-deps`. Currently this step takes 17 seconds and hopefully this
will dramatically reduce it.
> Cache dependencies

- .github/workflows/ci.yml
Unfortunately, this seems to slow things down (20 - 45 seconds) rather
than speed them up (~17 seconds previously). It makes the build harder
to understand too, so just remove caching again.
> Remove dependency caching

- store/redigostore/redigostore.go
Previously, we'd only selecting a DB when configured with one that was
non-0.
As reported in #70, this can be a problem if another subroutine using
the same pool changed a connection's DB and checked it back in. If that
were to occur and Throttled was configured with a DB of 0, then we'd end
up using the wrong DB. This is made possible because the Redigo adapter
allows a pool to be injected, so that pool may certainly be used
elsewhere.
Here we remove the conditional around the `SELECT` command and just
have it always run.
Fixes #70.
> Redigo: Always select a DB when procuring connection

- .github/workflows/ci.yml
- Makefile
Simplifies the CI build now that we're on Go Modules and the hackery to
use a traditional `GOPATH` isn't needed anymore.
We also remove `make get-deps` because Go Modules now does most of the
work for us. Go Lint is installed in its own named step in CI.
> Simplify the CI build

- store/goredisstore/goredisstore.go
This allows the use of the go-redis's `ClusterClient` besides the normal `Client`.
This change is fully backwards-compatible.
> Use interface for Redis client instead of implementation

- go.mod
- go.sum
There was some confusion in Redigo with respect to Go Modules, and some
projects, including this one, ended up on a "bad" 2.0.0 release that
wasn't meant to exist.
Here we try upgrading to the project's real current version, 1.8.4. See
releases [1].
Fixes #86.
[1] https://github.com/gomodule/redigo/tags
> "Upgrade" Redigo to 1.8.4

- store/redigostore/redigostore.go
- Add new interface RedigoPool for Redigo-based Redis pools.
- Use RedigoPool as the pool type for redigostore.
> Add support for redisc to redigostore

- .github/workflows/ci.yml
Add a couple more modern versions of Go to build in CI.
> Add Go 1.15 and 1.16 to CI matrix

- go.mod
- go.sum
- rate.go
- rate_test.go
Hi,
We've recently come in need of having a configurable retry limit (`maxCASAttemptsLimit`). Currently as is, this is a constant set to `10` - Which isn't flexible in certain use cases.
This PR adds a `NewGCRARateLimiterWithRetryLimit()` function which can take in a user defined retry limit. The current `NewGCRARateLimiter()` in place will make use of the existing maxCASAttemptsLimit of 10.
While here, I also noticed that the current logic was always retrying +1 times of the defined limit. Therefore it was always attempting a maximum of 11 times with the default max attempt limit of 10. I've addressed this so the limit comparison is greater than or equal to (as opposed to greater than only)
Let me know what you think
Relates to: https://github.com/throttled/throttled/issues/91
> Allow maxCASAttempts to be configurable

- .github/workflows/ci.yml
Add versions up to 1.19, and drop 1.12 which is very old, and seems to
be failing now.
Drop Golint, which as per its repo [1], is deprecated and frozen.
[1] https://github.com/golang/lint
> Add new Go versions, drop older version support, drop Golint

- README.md
- deprecated.go
- example_test.go
- http.go
- http_test.go
- rate.go
- rate_test.go
- store.go
- store/deprecated.go
- store/goredisstore/goredisstore.go
- store/goredisstore/goredisstore_test.go
- store/memstore/memstore.go
- store/memstore/memstore_test.go
- store/redigostore/redigostore.go
- store/redigostore/redigostore_test.go
- store/storetest/deprecated.go
- store/storetest/storetest.go
This allows the usage of stores that use a context, for example to cancel a request or to perform tracing. Saw this being discussed in https://github.com/throttled/throttled/pull/67 and https://github.com/throttled/throttled/issues/57.
All functions and interfaces that have changed signatures, have Ctx as a suffix to maintain full backwards compatibility and provide a smooth migration path. Or at least... I think so.
Not all context's are actually used yet. All the old stores just use an adapter around the old store that silently drops the provided context. But having it in the signature, allow the stores to be changed gradually. And I also have a PR incoming for using it with `redis-go.v8`.
Documentation can maybe use some work. So any suggestions regarding this or any feedback on the …
> Introduce context.Context in function signatures

- .github/workflows/ci.yml
A few tweaks for CI:
* Add Go 1.20.
* Move to checkout v3 action.
* Remove use of `go vet` which has been built into `go test` for some
time.
* Wrap Go versions in quotes so 1.20 isn't interpreted as "1.2".
> Add new Go version + a few tweaks to CI
